//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QA.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QA.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ArrayOfCriteria xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;Criteria&gt;
        ///		&lt;Id&gt;0&lt;/Id&gt;
        ///		&lt;Factor&gt;1. Надёжность&lt;/Factor&gt;
        ///		&lt;Name&gt;1.1. Устойчивость функционирования&lt;/Name&gt;
        ///		&lt;Mark&gt;Н1&lt;/Mark&gt;
        ///		&lt;Description&gt;Способность обеспечивать продолжение работы программы после возникновения отклонений, вызванных сбоями технических средств, ошибками во входных данных и ошибками обслуживания&lt;/Description&gt;
        ///	&lt;/Criteria&gt;
        ///	&lt;Criteria&gt;
        ///		&lt;Id&gt;1&lt;/Id&gt;
        ///		&lt;Fa [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Criteria {
            get {
                return ResourceManager.GetString("Criteria", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ArrayOfIndicator xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;Indicator&gt;
        ///		&lt;Id&gt;0&lt;/Id&gt;
        ///		&lt;Code&gt;Н0101&lt;/Code&gt;
        ///		&lt;Description&gt;Наличие требований к программе по устойчивости функционирования при наличии ошибок во входных данных&lt;/Description&gt;
        ///		&lt;IdMethod&gt;-1&lt;/IdMethod&gt;
        ///	&lt;/Indicator&gt;
        ///	&lt;Indicator&gt;
        ///		&lt;Id&gt;1&lt;/Id&gt;
        ///		&lt;Code&gt;Н0102&lt;/Code&gt;
        ///		&lt;Description&gt;Возможность обработки ошибочных ситуаций&lt;/Description&gt;
        ///		&lt;IdMethod&gt;-1&lt;/IdMethod&gt;
        ///	&lt;/Indicat [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Indicators {
            get {
                return ResourceManager.GetString("Indicators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ArrayOfPhase xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;Phase&gt;
        ///		&lt;Id&gt;0&lt;/Id&gt;
        ///		&lt;Name&gt;Анализ&lt;/Name&gt;
        ///		&lt;Step&gt;—&lt;/Step&gt;
        ///		&lt;Result&gt;Определение требований. Спецификация требований. Техническое задание&lt;/Result&gt;
        ///	&lt;/Phase&gt;
        ///	&lt;Phase&gt;
        ///		&lt;Id&gt;1&lt;/Id&gt;
        ///		&lt;Name&gt;Проектирование&lt;/Name&gt;
        ///		&lt;Step&gt;Логическое проектирование&lt;/Step&gt;
        ///		&lt;Result&gt;Логический проект (функциональный проект). Программно-технический проект: системы, программ, модулей, документаци [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string LifeCyclePhases {
            get {
                return ResourceManager.GetString("LifeCyclePhases", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ArrayOfMetric xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;Metric&gt;
        ///		&lt;Id&gt;0&lt;/Id&gt;
        ///		&lt;CriteriaId&gt;0&lt;/CriteriaId&gt;
        ///		&lt;PhaseId&gt;0&lt;/PhaseId&gt;
        ///		&lt;Metrics&gt;Н01 Н02&lt;/Metrics&gt;
        ///	&lt;/Metric&gt;
        ///	&lt;Metric&gt;
        ///		&lt;Id&gt;1&lt;/Id&gt;
        ///		&lt;CriteriaId&gt;0&lt;/CriteriaId&gt;
        ///		&lt;PhaseId&gt;1&lt;/PhaseId&gt;
        ///		&lt;Metrics&gt;Н01 Н02 Н03&lt;/Metrics&gt;
        ///	&lt;/Metric&gt;
        ///	&lt;Metric&gt;
        ///		&lt;Id&gt;2&lt;/Id&gt;
        ///		&lt;CriteriaId&gt;0&lt;/CriteriaId&gt;
        ///		&lt;PhaseId&gt;2&lt;/PhaseId&gt;
        ///		&lt;Metrics&gt;Н01 Н02 Н03&lt;/Metrics&gt;
        ///	&lt;/Metric&gt;
        ///	&lt;Metric&gt;
        ///		 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Metrics {
            get {
                return ResourceManager.GetString("Metrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;ArrayOfSoftwareTool xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;&gt;
        ///	&lt;SoftwareTool&gt;
        ///		&lt;Id&gt;0&lt;/Id&gt;
        ///		&lt;IdGOST&gt;5011&lt;/IdGOST&gt;
        ///		&lt;Description&gt;Операционные системы и средства их расширения&lt;/Description&gt;
        ///	&lt;/SoftwareTool&gt;
        ///	&lt;SoftwareTool&gt;
        ///		&lt;Id&gt;1&lt;/Id&gt;
        ///		&lt;IdGOST&gt;5012&lt;/IdGOST&gt;
        ///		&lt;Description&gt;Программные средства управления базами данных&lt;/Description&gt;
        ///	&lt;/SoftwareTool&gt;
        ///	&lt;SoftwareTool&gt;
        ///		&lt;Id&gt;2&lt;/Id&gt;
        ///		&lt;IdGOST&gt;5013&lt;/IdGOST&gt;
        ///		&lt;Description&gt;Инструм [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string SoftwareTools {
            get {
                return ResourceManager.GetString("SoftwareTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 1 1 1 1 1 1 1 -1 0 1 0 0
        ///1 1 1 1 1 1 1 1 1 1 1 0
        ///0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 0 0 0 0 -1 0 0 0 0
        ///0 0 0 0 0 0 0 -1 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0
        ///0 0 0 1 1 1 1 0 1 0 0 0
        ///1 1 1 1 1 1 1 1 1 1 1 0
        ///1 1 0 1 1 1 1 -1 1 1 0 0
        ///0 0 0 0 0 0 0 -1 0 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0
        ///1 1 1 0 0 1 0 -1 0 0 0 0
        ///-1 0 -1 0 0 -1 -1 -1 1 0 0 0
        ///0 0 0 0 0 0 0 0 0 0 0 0
        ///1 1 0 0 0 0 0 -1 0 0 0 0
        ///1 1 1 1 1 1 1 1 1 1 1 0
        ///1 1 1 1 1 1 1 1 1 1 1 0
        ///1 1 1 1 1 1 1 1 1 1 1 0
        ///1 1 1 1 1 1 1 1 1 1 1 0.
        /// </summary>
        internal static string SoftwareToolsAndCritariaMatrix {
            get {
                return ResourceManager.GetString("SoftwareToolsAndCritariaMatrix", resourceCulture);
            }
        }
    }
}
